steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: MSBuild Restore
        run: msbuild **/*.sln /t:Restore /p:Configuration=Release

      - name: MSBuild Build
        run: msbuild **/*.sln /p:Configuration=Release /p:UapAppxPackageBuildMode=SideloadOnly

      - name: Run Tests
        # Здесь используем специфичный рантайм, который ты указал в csproj
        run: dotnet test --configuration Release --runtime win-x64 --no-build --collect:"XPlat Code Coverage"

      - name: Generate Report
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator -reports:"**/TestResults/**/coverage.cobertura.xml" -targetdir:coverage -reporttypes:Html
